# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import socket_route_guide_pb2 as socket__route__guide__pb2


class SocketGRPCStub(object):
    """Simple RPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSocketRequest = channel.unary_unary(
                '/SocketGRPC/SendSocketRequest',
                request_serializer=socket__route__guide__pb2.MsgRequest.SerializeToString,
                response_deserializer=socket__route__guide__pb2.MsgReply.FromString,
                )


class SocketGRPCServicer(object):
    """Simple RPC
    """

    def SendSocketRequest(self, request, context):
        """Sends a setup request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SocketGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSocketRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSocketRequest,
                    request_deserializer=socket__route__guide__pb2.MsgRequest.FromString,
                    response_serializer=socket__route__guide__pb2.MsgReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SocketGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SocketGRPC(object):
    """Simple RPC
    """

    @staticmethod
    def SendSocketRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SocketGRPC/SendSocketRequest',
            socket__route__guide__pb2.MsgRequest.SerializeToString,
            socket__route__guide__pb2.MsgReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
