# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.utils.cmd_pb2 as cmd__pb2


class CommandGRPCStub(object):
    """Simple RPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCommandRequest = channel.unary_unary(
                '/CommandGRPC/SendCommandRequest',
                request_serializer=cmd__pb2.MsgRequest.SerializeToString,
                response_deserializer=cmd__pb2.MsgReply.FromString,
                )


class CommandGRPCServicer(object):
    """Simple RPC
    """

    def SendCommandRequest(self, request, context):
        """Sends a command request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCommandRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommandRequest,
                    request_deserializer=cmd__pb2.MsgRequest.FromString,
                    response_serializer=cmd__pb2.MsgReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommandGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommandGRPC(object):
    """Simple RPC
    """

    @staticmethod
    def SendCommandRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CommandGRPC/SendCommandRequest',
            cmd__pb2.MsgRequest.SerializeToString,
            cmd__pb2.MsgReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
